{{- $fullname := include "researchforge.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "researchforge.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8001
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "researchforge.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 3010
      targetPort: http
